#!/bin/bash

#Le script liste le nom de chaque fichier présent dans un dossier donné en paramètre
if [ $# != 1 ]
then
        #si il n'y a pas d'argument ou trop d'argument spécifié alors on renvoie 
        #le message d'erreur et on termine le code
        echo "Missing directory name"
        exit 1
else
        if [ -d "$1" ]    
        then
                #si le dossier fourni est un chemin d'accès qui existe
                #alors on liste le nom des fichiers qu'il contient
                for file in "$1"/*; do        #boucle sur chaque élément du dossier
                    if [ -f "$file" ]      #vérifie si l'élément est un fichier, si oui on l'affiche en sortie
                    then    
                        echo "$file"       #retourne le nom du fichier
                    fi 
                done        #fin de la boucle while
        else
                #sinon on renvoie un message d'erreur ainsi qu'on termine le code
                echo "The specified path is not a directory"
                exit 2
    fi
fi
